theme: jekyll-theme-slate
logo: "assets/images/profile_small.jpg"
title: Natalie Yoh
description: _PhD candidate Durrell Institute of Conservation & Ecology (DICE)_ 
image: "assets/images/profile_small.jpg"
