theme: jekyll-theme-minimal

.site-title::before {
content: url("(https://user-images.githubusercontent.com/43967474/143014893-bdeceaba-3870-4dab-92fb-1f2bfd3879a6.jpg");
display: inline-block;
position: relative;
width: 32px;
top: 32px;
}
